import numpy as np
from dataclasses import dataclass, field
from typing import Callable, Literal, Optional
from comnumpy.core import Processor


@dataclass(slots=True)
class Laser(Processor):
    r"""Continuous-wave laser envelope generator with Wiener phase noise.

    Signal Model
    ------------
    The generated complex envelope is

    .. math::

        E[n] = \sqrt{P_s} \,
        e^{j \left(2 \pi \Delta f \, n T_s + \theta_0 + \theta[n]\right)},
        \qquad
        \theta[n] = \sum_{k=0}^{n} \delta\theta_k, \qquad
        \delta\theta_k \sim
        \mathcal{N}\left(0, \tfrac{2 \pi \Delta\nu}{f_s}\right)

    where :math:`P_s = 10^{(P_{dBm} - 30)/10}` is the emitted power in W,
    :math:`T_s = 1/f_s` the sampling period, :math:`\Delta f` the carrier
    frequency offset and :math:`\theta[n]` a Wiener phase noise of
    linewidth :math:`\Delta\nu`.

    Axes: *generator* -- consumes a sample count ``nb_samples`` and
    produces a 1D complex envelope (N,).

    Parameters
    ----------
    P_dBm : float
        Laser power :math:`P_{dBm}` in dBm. Default is -10.
    linewidth : float, keyword-only
        Laser linewidth :math:`\Delta\nu` in Hz. Default is 0 (no phase
        noise).
    theta0 : float, optional, keyword-only
        Initial phase :math:`\theta_0` in rad. Drawn at random when None.
    seed : int, optional, keyword-only
        Local RNG seed (for :math:`\theta_0` and the phase noise).
    fs : float, keyword-only
        Sampling frequency :math:`f_s` in Hz. Default is 1e9.
    freq_offset : float, keyword-only
        Carrier frequency offset :math:`\Delta f` in Hz, relative to the
        nominal laser wavelength. Default is 0.
    name : str, optional, keyword-only
        Name of the laser instance. Default is ``"Laser"``.

    References
    ----------
    T. Pfau, S. Hoffmann, R. Noe, "Hardware-Efficient Coherent Digital
    Receiver Concept With Feedforward Carrier Recovery for M-QAM
    Constellations," Journal of Lightwave Technology, vol. 27, no. 8,
    pp. 989-999, 2009.

    Examples
    --------
    >>> laser = Laser(0, linewidth=0, theta0=0.0, fs=1e9)
    >>> E = laser(3)
    >>> print(np.round(np.abs(E) ** 2, 6))
    [0.001 0.001 0.001]
    """
    P_dBm: float = -10
    linewidth: float = field(default=0, kw_only=True)
    theta0: Optional[float] = field(default=None, kw_only=True)
    seed: Optional[int] = field(default=None, kw_only=True)
    fs: float = field(default=1e9, kw_only=True)
    freq_offset: float = field(default=0, kw_only=True)
    name: str = field(default="Laser", kw_only=True)
    # internal state (declared for slots, D40a)
    rng: Optional[np.random.Generator] = field(init=False, repr=False, default=None)

    def __post_init__(self):
        self.rng = np.random.default_rng(self.seed)

    def forward(self, nb_samples: object) -> np.ndarray:
        # a source: it takes a length, like SymbolGenerator (D2)
        assert isinstance(nb_samples, int)
        assert self.rng is not None      # set in __post_init__
        if not isinstance(self.theta0, (float, int)):
            theta_0 = 2*np.pi*self.rng.standard_normal() - np.pi
        else:
            theta_0 = self.theta0

        dtheta = np.sqrt(2*np.pi*self.linewidth/self.fs)*self.rng.standard_normal(nb_samples)
        theta = np.cumsum(dtheta)
        Ps = 10**((self.P_dBm-30)/10)
        T_s = 1/self.fs
        t = np.arange(nb_samples)*T_s
        E_laser = np.sqrt(Ps)*np.exp(1j*(2*np.pi*self.freq_offset*t+theta_0+theta))
        return E_laser


@dataclass(slots=True)
class Optical90HybridCircuit(Processor):
    r"""Optical 90-degree hybrid front-end for coherent detection.

    Signal Model
    ------------
    In the ideal mode, the optic-electro conversion is transparent:

    .. math::

        y[n] = x[n]

    In the non-ideal mode, the incoming field is mixed with the local
    oscillator laser :math:`E_{lo}[n]` and scaled by the receiver
    sensitivity :math:`\rho`:

    .. math::

        y[n] = \rho \, x[n] \, E_{lo}^*[n]

    where :math:`E_{lo}[n]` is generated by ``laser_in`` (unit amplitude
    when no laser is provided).

    Axes: *element-wise* -- applied pointwise; the local-oscillator
    realization is drawn per sample of a 1D signal (N,).

    Parameters
    ----------
    is_ideal : bool
        If True, ideal conversion (identity). If False, mixing with the
        local oscillator and sensitivity scaling. Default is True.
    sensitivity : float, keyword-only
        Sensitivity factor :math:`\rho` of the circuit (non-ideal mode).
        Default is 0.6.
    laser_in : Laser, optional, keyword-only
        Local oscillator laser generating :math:`E_{lo}[n]`. Default is
        None (unit-amplitude local oscillator).
    name : str, optional, keyword-only
        Name of the device instance. Default is ``"Optical90HybridCircuit"``.

    References
    ----------
    K. Kikuchi, "Fundamentals of coherent optical fiber communications,"
    Journal of Lightwave Technology, vol. 34, no. 1, pp. 157-179, 2016.

    Examples
    --------
    >>> x = np.array([1 + 1j, -1 + 0.5j])
    >>> y = Optical90HybridCircuit()(x)
    >>> bool(np.array_equal(y, x))
    True
    """
    is_ideal: bool = True
    sensitivity: float = field(default=0.6, kw_only=True)
    laser_in: Optional[Callable[..., np.ndarray]] = field(default=None, kw_only=True)
    name: str = field(default="Optical90HybridCircuit", kw_only=True)

    def forward(self, x: np.ndarray) -> np.ndarray:
        if self.is_ideal:
            y = x
        else:
            if self.laser_in:
                E_laser = self.laser_in(len(x))
            else:
                E_laser = np.ones(len(x))

            y = self.sensitivity * x * np.conj(E_laser)
            y = np.real(y) + 1j*np.imag(y)
        return y


@dataclass(slots=True)
class PowerControl(Processor):
    r"""Rescales a signal to a target power level.

    Signal Model
    ------------
    .. math::

        y[n] = g \, x[n], \qquad
        g = \begin{cases}
        P_{target} / \sqrt{P_x} & \text{(natural)} \\[4pt]
        \sqrt{10^{(P_{target} - 30)/10}} / \sqrt{P_x} & \text{(dBm)}
        \end{cases}

    where :math:`P_x = \mathbb{E}\left[|x[n]|^2\right]` is the measured
    input power and :math:`P_{target}` the target level. In ``"dBm"``
    mode the output power is :math:`10^{(P_{target} - 30)/10}` W; in
    ``"natural"`` mode the output RMS amplitude is :math:`P_{target}`.

    Axes: *element-wise* -- pointwise scaling; the gain :math:`g` is
    estimated from the whole array.

    Parameters
    ----------
    P_moy : float
        Target level :math:`P_{target}`; interpreted according to
        ``unit``. Default is 1.
    unit : {"natural", "dBm"}, keyword-only
        Unit of ``P_moy``. Default is ``"natural"``.
    name : str, optional, keyword-only
        Name of the device instance. Default is ``"power_control"``.

    Examples
    --------
    >>> x = np.array([2.0, -2.0, 2.0, -2.0])
    >>> y = PowerControl(1)(x)
    >>> print(y)
    [ 1. -1.  1. -1.]
    """
    P_moy: float = 1
    unit: Literal["natural", "dBm"] = field(default="natural", kw_only=True)
    name: str = field(default="power_control", kw_only=True)

    def get_gain(self, P_moy_x: float) -> float:
        if self.unit == 'dBm':
            gain = np.sqrt(10**((self.P_moy-30)/10))/P_moy_x
        else:
            gain = self.P_moy/P_moy_x
        return gain

    def forward(self, x: np.ndarray) -> np.ndarray:
        P_moy_x = np.sqrt(np.mean(np.abs(x)**2))
        gain = self.get_gain(P_moy_x)
        y = gain*x
        return y


@dataclass(slots=True)
class ErbiumDopedFiberAmplifier(Processor):
    r"""Erbium-doped fiber amplifier (EDFA): flat gain plus additive ASE noise.

    Signal Model
    ------------
    .. math::

        y[n] = \sqrt{G} \, x[n] + b[n], \qquad
        b[n] \sim \mathcal{CN}\left(0, N_{\mathrm{ase}}\right)

    where :math:`\sqrt{G}` is the amplitude gain of the amplifier and
    :math:`N_{\mathrm{ase}}` the variance of the circular amplified
    spontaneous emission (ASE) noise, per state of polarization.

    Axes: *element-wise* -- pointwise gain plus additive noise; the ASE
    realization is drawn per sample of a 1D signal (N,).

    Parameters
    ----------
    gain : float
        Amplitude gain :math:`\sqrt{G}` (linear).
    N_ase : float
        ASE noise variance :math:`N_{\mathrm{ase}}` (in W), per state of
        polarization.
    seed : int, optional, keyword-only
        Local RNG seed.
    name : str, optional, keyword-only
        Name of the amplifier instance. Default is
        ``"ErbiumDopedFiberAmplifier"``.

    References
    ----------
    * R.-J. Essiambre, G. Kramer, P. J. Winzer, G. J. Foschini and B. Goebel,
      "Capacity limits of optical fiber networks," Journal of Lightwave
      Technology, vol. 28, no. 4, pp. 662-701, 2010.
    * https://www.sciencedirect.com/topics/engineering/spontaneous-emission-factor

    Examples
    --------
    >>> x = np.ones(3, dtype=complex)
    >>> y = ErbiumDopedFiberAmplifier(2.0, 0.0)(x)
    >>> print(y)
    [2.+0.j 2.+0.j 2.+0.j]
    """
    gain: float
    N_ase: float
    name: str = field(default="ErbiumDopedFiberAmplifier", kw_only=True)
    seed: Optional[int] = field(default=None, kw_only=True)
    # internal state (declared for slots, D40a)
    rng: Optional[np.random.Generator] = field(init=False, repr=False, default=None)

    def __post_init__(self):
        self.rng = np.random.default_rng(self.seed)

    def forward(self, x: np.ndarray) -> np.ndarray:
        assert self.rng is not None      # set in __post_init__
        N = len(x)
        scale = np.sqrt(self.N_ase/2)
        b = self.rng.normal(scale=scale, size=N) + 1j * self.rng.normal(scale=scale, size=N)
        y = self.gain * x + b
        return y


@dataclass(slots=True)
class MachZehnderModulator(Processor):
    r"""IQ Mach-Zehnder modulator (MZM).

    Signal Model
    ------------
    In the ideal mode, the modulation is linear:

    .. math::

        y[n] = -\frac{\pi V_{pp}}{4 V_\pi} \, E_{laser}[n] \, x[n]

    In the non-ideal mode, each branch applies its cosine transfer
    function to the drive voltages:

    .. math::

        y[n] = \left[
        \cos\left(\frac{\pi \, u_I[n]}{2 V_\pi}\right)
        + e^{j \Phi} \cos\left(\frac{\pi \, u_Q[n]}{2 V_\pi}\right)
        \right] E_{laser}[n]

    .. math::

        u_I[n] = V_\pi + \frac{g_I}{2} \frac{V_{pp}}{m} \, \Re(x[n]),
        \qquad
        u_Q[n] = V_\pi + \frac{g_Q}{2} \frac{V_{pp}}{m} \, \Im(x[n])

    where :math:`V_\pi` is the half-wave voltage, :math:`V_{pp} = k V_\pi`
    the peak-to-peak drive voltage, :math:`g_I` and :math:`g_Q = 2 - g_I`
    the branch gains, :math:`\Phi` the I/Q phase offset,
    :math:`m = \max(\max|\Re(x)|, \max|\Im(x)|)` a normalization
    coefficient and :math:`E_{laser}[n]` the input laser field (unit
    amplitude when no laser is provided).

    Axes: *element-wise* -- applied pointwise; the normalization
    :math:`m` is estimated from the whole array and the laser realization
    is drawn per sample of a 1D signal (N,).

    Parameters
    ----------
    is_ideal : bool
        If True, ideal linear modulation without imbalance. Default is
        False.
    Vpi : float, keyword-only
        Half-wave voltage :math:`V_\pi` in V. Default is 6.
    k : float, keyword-only
        Peak-to-peak drive ratio :math:`k = V_{pp} / V_\pi`. Default is 1.
    gI : float, keyword-only
        Gain :math:`g_I` of the I branch (the Q branch gets
        :math:`g_Q = 2 - g_I`). Default is 1.
    Phi : float, keyword-only
        Phase offset :math:`\Phi` between the I and Q branches in rad.
        Default is ``np.pi / 2``.
    laser_in : callable, optional, keyword-only
        Input laser field generator producing :math:`E_{laser}[n]`.
        Default is None (unit-amplitude field).
    name : str, optional, keyword-only
        Name of the modulator instance. Default is
        ``"MachZehnderModulator"``.

    References
    ----------
    C. Peucheret, "Generation and Detection of Optical Modulation
    Formats," Technical University of Denmark, 2012.

    Examples
    --------
    >>> mzm = MachZehnderModulator(is_ideal=True, Vpi=6.0, k=1.0)
    >>> y = mzm(np.array([1.0 + 0j]))
    >>> print(round(float(np.real(y[0])), 4))
    -0.7854
    """

    is_ideal: bool = False
    Vpi: float = field(default=6, kw_only=True)
    k: float = field(default=1, kw_only=True)
    gI: float = field(default=1, kw_only=True)
    Phi: float = field(default=np.pi / 2, kw_only=True)
    laser_in: Optional[Callable[..., np.ndarray]] = field(default=None, kw_only=True)
    name: str = field(default="MachZehnderModulator", kw_only=True)
    # internal state (declared for slots, D40a)
    Vpp: float = field(init=False, repr=False, default=0.0)
    VdcI: float = field(init=False, repr=False, default=0.0)
    VdcQ: float = field(init=False, repr=False, default=0.0)

    def __post_init__(self):
        self.Vpp = self.k * self.Vpi
        self.VdcI = self.Vpi
        self.VdcQ = self.Vpi

    def forward(self, x: np.ndarray) -> np.ndarray:
        m = max(np.max(np.abs(np.real(x))), np.max(np.abs(np.imag(x))))  # normalization coeff

        if self.laser_in is not None:
            E_laser = self.laser_in(len(x))
        else:
            E_laser = np.ones(len(x))  # ideal laser

        if self.is_ideal:
            y = -np.pi / 2 * self.Vpp / (2 * self.Vpi) * E_laser * x
        else:
            gQ = 1 - (self.gI - 1)  # Gain on Q branch
            uIt = self.VdcI + self.gI / 2 * self.Vpp / m * np.real(x)
            uQt = self.VdcQ + gQ / 2 * self.Vpp / m * np.imag(x)
            y = (np.cos(np.pi / 2 / self.Vpi * uIt) + np.exp(1j * self.Phi) * np.cos(np.pi / 2 / self.Vpi * uQt)) * E_laser
        return y
