flowchart LR
    upsampler["Upsampler"]
    srrcfilter["SRRCFilter"]
    signal_amplifier["Amplifier"]
    fibre["FiberLink"]
    dbp["DBP"]
    srrcfilter_2["SRRCFilter"]
    downsampler["Downsampler"]
    signal_amplifier_2["Amplifier"]
    upsampler --> srrcfilter
    srrcfilter --> signal_amplifier
    signal_amplifier --> fibre
    fibre --> dbp
    dbp --> srrcfilter_2
    srrcfilter_2 --> downsampler
    downsampler --> signal_amplifier_2