flowchart LR
    source["SymbolGenerator"]
    tx["SymbolMapper"]
    launch["Amplifier"]
    upsampler["Upsampler"]
    srrcfilter["SRRCFilter"]
    fibre["FiberLink"]
    dbp["DBP"]
    srrcfilter_2["SRRCFilter"]
    downsampler["Downsampler"]
    source --> tx
    tx --> launch
    launch --> upsampler
    upsampler --> srrcfilter
    srrcfilter --> fibre
    fibre --> dbp
    dbp --> srrcfilter_2
    srrcfilter_2 --> downsampler
    classDef tapped stroke-dasharray: 4 2
    class tx tapped