flowchart LR
    data_tx["SymbolGenerator"]
    symbol_mapper["SymbolMapper"]
    ofdm_transmitter["OFDMTransmitter"]
    fir["FIRChannel"]
    data_rx["AWGN"]
    data_rx_eq["OFDMReceiver"]
    symbol_demapper["SymbolDemapper"]
    data_tx --> symbol_mapper
    symbol_mapper --> ofdm_transmitter
    ofdm_transmitter --> fir
    fir --> data_rx
    data_rx --> data_rx_eq
    data_rx_eq --> symbol_demapper
    classDef tapped stroke-dasharray: 4 2
    class data_tx,data_rx_eq tapped