flowchart LR
    s2_p["Serial2Parallel"]
    cp_remover["CyclicPrefixRemover"]
    fft["FFTProcessor"]
    frequency_domain_equalizer["FrequencyDomainEqualizer"]
    carrier_extractor["CarrierExtractor"]
    p2_s["Parallel2Serial"]
    s2_p --> cp_remover
    cp_remover --> fft
    fft --> frequency_domain_equalizer
    frequency_domain_equalizer --> carrier_extractor
    carrier_extractor --> p2_s