flowchart LR
    data_tx["SymbolGenerator"]
    symbol_mapper["SymbolMapper"]
    ofdm_transmitter["OFDMTransmitter"]
    fir["FIRChannel"]
    awgn["AWGN"]
    data_rx["OFDMReceiver"]
    symbol_demapper["SymbolDemapper"]
    data_tx --> symbol_mapper
    symbol_mapper --> ofdm_transmitter
    ofdm_transmitter --> fir
    fir --> awgn
    awgn --> data_rx
    data_rx --> symbol_demapper
    classDef tapped stroke-dasharray: 4 2
    class data_tx,data_rx tapped