flowchart LR
    s2_p["Serial2Parallel"]
    carrier_allocator_tx["CarrierAllocator"]
    ifft["IFFTProcessor"]
    cp_adder["CyclicPrefixer"]
    p2_s["Parallel2Serial"]
    s2_p --> carrier_allocator_tx
    carrier_allocator_tx --> ifft
    ifft --> cp_adder
    cp_adder --> p2_s