"""Multipath fading: delay profiles and Doppler processes (decision D43).

The delay axis gets the treatment decisions D15/D17/D20 gave the
frequency axis: a frozen value object carrying the numbers *and* their
provenance, a registry-backed catalog of standard models, and a
self-check at construction against the figures published alongside the
table. ``CarrierType`` types the frequency axis, ``FieldRole`` the frame
axis, and :class:`PowerDelayProfile` now describes the delay axis.

A standardized channel model is a power delay profile **plus** a Doppler
spectrum; both live here. The taps are generated by
:func:`rayleigh_process`, and applied to a signal by
:class:`~comnumpy.core.channels.TappedDelayLineChannel`.
"""
from __future__ import annotations

import logging

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Callable, Optional

import numpy as np

from comnumpy.exceptions import ShapeError

logger = logging.getLogger(__name__)

__all__ = [
    "DopplerSpectrum", "PowerDelayProfile", "rayleigh_process",
    "get_delay_profile", "register_delay_profile", "available_delay_profiles",
]


class DopplerSpectrum(Enum):
    """Shape of the Doppler power spectrum of a tap."""

    CLASSICAL = "classical"   # Clarke/Jakes U shape, isotropic scattering
    FLAT = "flat"             # uniform over [-f_D, f_D]
    STATIC = "static"         # no time variation (block fading)


def _classical_bin_powers(lo: np.ndarray, hi: np.ndarray,
                          f_doppler: float) -> np.ndarray:
    r"""Exact power of the classical spectrum inside each frequency bin.

    The Clarke/Jakes density
    :math:`S(f) = 1 / (\pi f_D \sqrt{1 - (f/f_D)^2})` has integrable
    singularities at :math:`\pm f_D`, so sampling it on the FFT grid
    returns infinities. Its primitive is known --
    :math:`\arcsin(f/f_D)/\pi` -- so the power of the bin
    :math:`[f_{lo}, f_{hi}]` is a difference of arcsines, finite
    everywhere and exact.
    """
    cdf_hi = np.arcsin(np.clip(hi / f_doppler, -1.0, 1.0)) / np.pi
    cdf_lo = np.arcsin(np.clip(lo / f_doppler, -1.0, 1.0)) / np.pi
    return cdf_hi - cdf_lo


def rayleigh_process(n_samples: int, fs: float, f_doppler: float, *,
                     spectrum: DopplerSpectrum = DopplerSpectrum.CLASSICAL,
                     rng: Optional[np.random.Generator] = None) -> np.ndarray:
    r"""Generate one complex Gaussian fading tap with a given Doppler spectrum.

    Signal Model
    ------------
    The tap gain :math:`h[n]` is a zero-mean complex Gaussian process,
    :math:`h[n] \sim \mathcal{CN}(0, 1)`, whose power spectral density is
    the Doppler spectrum of the model. For isotropic scattering
    (``CLASSICAL``, the Clarke/Jakes model) that density is

    .. math::

        S(f) = \frac{1}{\pi f_D \sqrt{1 - \left(f / f_D\right)^2}},
        \qquad |f| < f_D

    whose inverse Fourier transform gives the reference autocorrelation

    .. math::

        R(\tau) = \mathbb{E}\left[h[n] h^*[n + \tau f_s]\right]
                = J_0\!\left(2 \pi f_D \tau\right)

    with :math:`J_0` the Bessel function of the first kind, order zero --
    the quantity ``validation/fading_doppler.py`` checks.

    The process is synthesized **directly on the output FFT grid**: every
    bin overlapping the band is filled with a complex Gaussian shaped by
    the square root of the exact power it covers, and one inverse
    transform gives the samples. Weighting by the covered fraction rather
    than testing bin centres matters near :math:`\pm f_D`, where the
    density is singular and one bin carries several percent of the band. Nothing is resampled or interpolated, so
    the realization is band-limited by construction. The known cost of the
    spectral method is periodicity: the realization repeats with period
    ``n_samples / fs``.

    When the observation window is shorter than one Doppler period
    (:math:`n\_samples / f_s < 1 / f_D`), no bin fits under :math:`f_D`
    and the tap is constant over the window -- which is the physically
    correct answer, not a degenerate case: the channel simply has no time
    to vary.

    Axes: returns a 1D array of length ``n_samples``.

    Parameters
    ----------
    n_samples : int
        Number :math:`N` of samples to generate.
    fs : float
        Sampling frequency :math:`f_s` of the signal, in Hz.
    f_doppler : float
        Maximum Doppler frequency :math:`f_D` in Hz, i.e. :math:`v / \lambda`.
        Zero gives a constant tap.
    spectrum : DopplerSpectrum, optional, keyword-only
        Shape of :math:`S(f)`. Default ``CLASSICAL``.
    rng : numpy.random.Generator, optional, keyword-only
        Random generator; a fresh default one when omitted.

    Returns
    -------
    numpy.ndarray
        Complex tap gains of length ``n_samples`` and unit variance.

    References
    ----------
    R. H. Clarke, "A statistical theory of mobile-radio reception", Bell
    System Technical Journal 47(6), 1968; W. C. Jakes, *Microwave Mobile
    Communications*, Wiley, 1974, Chapter 1.

    Notes
    -----
    The average power of a *single* realization is itself random: the
    process has about :math:`2 N f_D / f_s` degrees of freedom over the
    window, so a short look at a slowly fading channel does not average
    its own power out (standard deviation 0.16 for 260 ms at
    :math:`f_D = 100` Hz). The ensemble mean is exactly one; the
    realization is deliberately **not** renormalized, which would break
    the Gaussian statistics.

    Examples
    --------
    >>> rng = np.random.default_rng(0)
    >>> h = rayleigh_process(1024, fs=1e3, f_doppler=10.0, rng=rng)
    >>> h.shape, bool(np.std(np.abs(h)) > 0)      # the tap does vary
    ((1024,), True)
    >>> static = rayleigh_process(64, fs=1e3, f_doppler=0.0, rng=rng)
    >>> bool(np.allclose(static, static[0]))      # no Doppler, no variation
    True
    """
    if n_samples <= 0:
        raise ValueError(f"n_samples must be positive, got {n_samples}")
    if fs <= 0:
        raise ValueError(f"fs must be positive, got {fs}")
    if f_doppler < 0:
        raise ValueError(f"f_doppler must be non-negative, got {f_doppler}")
    rng = np.random.default_rng() if rng is None else rng

    if f_doppler == 0 or spectrum is DopplerSpectrum.STATIC:
        gain = (rng.normal(scale=np.sqrt(0.5))
                + 1j * rng.normal(scale=np.sqrt(0.5)))
        return np.full(n_samples, gain, dtype=complex)

    freq = np.fft.fftfreq(n_samples, d=1 / fs)
    df = fs / n_samples
    lo, hi = freq - df / 2, freq + df / 2
    # A bin counts when it *overlaps* the band, not when its centre falls
    # inside it: near +/-f_D the classical density is singular, so an edge
    # bin carries several percent of the band power, and a centre test
    # keeps or drops it whole depending on where the grid happens to land
    # (up to 8.3% of the band lost, and a knife edge when f_D sits on a bin
    # centre). The primitives below already clip to the band, so the power
    # of a partially covered bin comes out exact.
    if spectrum is DopplerSpectrum.CLASSICAL:
        power = np.maximum(_classical_bin_powers(lo, hi, f_doppler), 0.0)
    elif spectrum is DopplerSpectrum.FLAT:
        overlap = np.minimum(hi, f_doppler) - np.maximum(lo, -f_doppler)
        power = np.maximum(overlap, 0.0)
    else:                                       # pragma: no cover - enum guard
        raise ValueError(f"unknown Doppler spectrum {spectrum!r}")

    if not np.any(power[1:] > 0):
        # Window shorter than one Doppler period: the tap cannot vary. This
        # is easy to hit unnoticed -- EVA at 70 Hz and 15.36 MHz needs
        # 219 000 samples before the channel moves at all -- so say it (D11)
        # rather than let a block-fading result pass for a time-selective one.
        logger.warning(
            "%s samples at fs=%.4g Hz span %.3g s, less than one Doppler "
            "period 1/f_D = %.3g s: the tap is constant over this call "
            "(block fading). Simulate a longer window to see time selectivity.",
            n_samples, fs, n_samples / fs, 1 / f_doppler)
        gain = (rng.normal(scale=np.sqrt(0.5))
                + 1j * rng.normal(scale=np.sqrt(0.5)))
        return np.full(n_samples, gain, dtype=complex)

    total = power.sum()
    if total <= 0:                              # pragma: no cover - guarded above
        raise ValueError("the Doppler spectrum carries no power in band")
    shaping = np.sqrt(power / total)

    white = (rng.normal(size=n_samples) + 1j * rng.normal(size=n_samples))
    spectrum_samples = shaping * white
    h = np.fft.ifft(spectrum_samples) * n_samples / np.sqrt(2)
    return h


@dataclass(frozen=True, slots=True)
class PowerDelayProfile:
    r"""Tapped-delay-line model of a multipath channel (decision D43).

    Signal Model
    ------------
    The channel is a sum of :math:`L` resolvable paths, path :math:`l`
    arriving with delay :math:`\tau_l` and average power :math:`P_l`:

    .. math::

        h(t, \tau) = \sum_{l=0}^{L-1} a_l(t) \, \delta(\tau - \tau_l),
        \qquad \mathbb{E}\left[|a_l(t)|^2\right] = \gamma_l

    The powers are normalized so that :math:`\sum_l \gamma_l = 1`: the
    delay spread then changes the frequency selectivity without changing
    the operating SNR, which is what makes two profiles comparable. Each
    :math:`a_l(t)` is a Rayleigh process with the model's Doppler
    spectrum (:func:`rayleigh_process`), or Rician when the tap carries a
    specular component.

    The summary figure of a profile is its RMS delay spread

    .. math::

        \sigma_\tau = \sqrt{\sum_l \gamma_l \tau_l^2
                            - \left(\sum_l \gamma_l \tau_l\right)^2}

    which sets the coherence bandwidth, roughly
    :math:`B_c \approx 1 / (5 \sigma_\tau)`.

    Parameters
    ----------
    delays_ns : sequence of float
        Path delays :math:`\tau_l` in nanoseconds, ascending.
    powers_dB : sequence of float
        Average path powers :math:`P_l` in dB, relative -- the profile is
        normalized to unit total power.
    doppler : DopplerSpectrum, optional, keyword-only
        Doppler spectrum shared by the taps. Default ``CLASSICAL``.
    rice_k_dB : float, optional, keyword-only
        Rice factor :math:`K` in dB of the **first** tap when the model
        has a line of sight (TDL-D/E of TR 38.901); ``None`` for a fully
        Rayleigh profile.
    standard : str, keyword-only
        Standard this profile comes from. Default ``"custom"``.
    reference : str, keyword-only
        Clause the numbers were copied from -- same provenance
        requirement as decision D20 for carrier allocations.

    Raises
    ------
    ValueError
        If the two sequences differ in length, if the delays are not
        strictly ascending, or if the profile carries no power.

    References
    ----------
    J. G. Proakis, M. Salehi, *Digital Communications*, 5th ed.,
    McGraw-Hill, 2008, Section 13.1 (multipath fading channels);
    3GPP TS 36.101 Annex B.2 and 3GPP TR 38.901 Section 7.7 for the
    catalog entries.

    Examples
    --------
    >>> profile = PowerDelayProfile([0, 100, 300], [0.0, -3.0, -6.0])
    >>> profile.n_taps, round(profile.rms_delay_spread_ns, 1)
    (3, 103.1)
    >>> print(np.round(profile.powers_lin, 4))
    [0.5707 0.286  0.1433]
    """

    delays_ns: np.ndarray
    powers_dB: np.ndarray
    doppler: DopplerSpectrum = field(default=DopplerSpectrum.CLASSICAL,
                                     kw_only=True)
    rice_k_dB: Optional[float] = field(default=None, kw_only=True)
    standard: str = field(default="custom", kw_only=True)
    reference: str = field(default="", kw_only=True)

    def __post_init__(self) -> None:
        delays = np.asarray(self.delays_ns, dtype=float)
        powers = np.asarray(self.powers_dB, dtype=float)
        if delays.ndim != 1 or powers.ndim != 1:
            raise ValueError(
                f"delays_ns and powers_dB must be 1D, got shapes "
                f"{delays.shape} and {powers.shape}")
        if delays.size != powers.size:
            raise ValueError(
                f"delays_ns has {delays.size} entries but powers_dB has "
                f"{powers.size}; one power per path is required")
        if delays.size == 0:
            raise ValueError("a delay profile needs at least one path")
        if np.any(np.diff(delays) <= 0) or delays[0] < 0:
            raise ValueError(
                f"delays_ns must be non-negative and strictly ascending, "
                f"got {delays.tolist()}")
        delays.setflags(write=False)
        powers.setflags(write=False)
        object.__setattr__(self, "delays_ns", delays)
        object.__setattr__(self, "powers_dB", powers)

    # -- derived quantities ---------------------------------------------
    @property
    def n_taps(self) -> int:
        """Number :math:`L` of resolvable paths."""
        return int(self.delays_ns.size)

    @property
    def powers_lin(self) -> np.ndarray:
        r"""Per-path powers :math:`\gamma_l`, normalized to unit sum."""
        linear = 10 ** (self.powers_dB / 10)
        return linear / linear.sum()

    @property
    def mean_delay_ns(self) -> float:
        r"""Power-weighted mean delay :math:`\sum_l \gamma_l \tau_l`, in ns."""
        return float(np.sum(self.powers_lin * self.delays_ns))

    @property
    def rms_delay_spread_ns(self) -> float:
        r"""RMS delay spread :math:`\sigma_\tau`, in nanoseconds."""
        weights = self.powers_lin
        mean = float(np.sum(weights * self.delays_ns))
        second = float(np.sum(weights * self.delays_ns ** 2))
        return float(np.sqrt(max(second - mean ** 2, 0.0)))

    @property
    def coherence_bandwidth_hz(self) -> float:
        r"""Coherence bandwidth :math:`B_c \approx 1 / (5 \sigma_\tau)`, in Hz.

        The 0.5-correlation rule of thumb; a conservative estimate, and
        the one Proakis quotes.
        """
        spread_s = self.rms_delay_spread_ns * 1e-9
        return float("inf") if spread_s == 0 else 1.0 / (5 * spread_s)

    def to_taps(self, fs: float) -> tuple[np.ndarray, np.ndarray]:
        r"""Resample the profile onto the sample grid of a signal.

        Path delays are rounded to the nearest sample, and paths that
        land on the same sample are **summed in power** -- the standard
        practice, and the reason a model is only meaningful above a
        minimum sampling rate.

        Parameters
        ----------
        fs : float
            Sampling frequency in Hz.

        Returns
        -------
        tuple of numpy.ndarray
            ``(sample_delays, powers)``: integer delays in samples, and
            the matching normalized powers summing to 1.

        Examples
        --------
        >>> profile = get_delay_profile("EVA")
        >>> delays, powers = profile.to_taps(fs=15.36e6)
        >>> delays.tolist()
        [0, 2, 5, 6, 11, 17, 27, 39]
        >>> round(float(powers.sum()), 12)
        1.0
        """
        if fs <= 0:
            raise ValueError(f"fs must be positive, got {fs}")
        sample_delays = np.rint(self.delays_ns * 1e-9 * fs).astype(int)
        unique = np.unique(sample_delays)
        powers = np.array([self.powers_lin[sample_delays == d].sum()
                           for d in unique])
        return unique, powers / powers.sum()

    # -- rendering (P7, same mechanism as the D21 spectral map) ---------
    def __repr__(self) -> str:
        header = f"{self.standard}"
        if self.reference:
            header += f"  [{self.reference}]"
        body = [header,
                f"{self.n_taps} paths | rms delay spread "
                f"{self.rms_delay_spread_ns:.1f} ns | coherence bandwidth "
                f"{self.coherence_bandwidth_hz / 1e3:.0f} kHz | "
                f"doppler {self.doppler.value}"]
        span = float(self.delays_ns[-1]) or 1.0
        width = 48
        floor_db = -30.0
        for delay, power in zip(self.delays_ns, self.powers_dB, strict=True):
            column = int(round(width * delay / span))
            height = max(0.0, (power - floor_db) / -floor_db)
            bar = " " * column + "#" * max(1, int(round(6 * height)))
            body.append(f"{delay:7.0f} ns {power:6.1f} dB |{bar}")
        return "\n".join(body)


# -- catalog (decision D17 mechanism, applied to the delay axis) --------

_PROFILE_REGISTRY: dict[str, Callable[..., PowerDelayProfile]] = {}


def register_delay_profile(name: str):
    """Register a catalog entry; users can add their own models.

    Parameters
    ----------
    name : str
        Name the factory answers to in :func:`get_delay_profile`. An
        existing name is replaced, which is what lets a user override a
        catalog model with their own measurement.

    Examples
    --------
    >>> @register_delay_profile("LAB")
    ... def _lab():
    ...     return PowerDelayProfile(delays_ns=(0.0, 100.0),
    ...                              powers_dB=(0.0, -3.0),
    ...                              standard="LAB", reference="bench")
    >>> get_delay_profile("LAB").n_taps
    2
    """
    def decorator(func: Callable[..., PowerDelayProfile]):
        _PROFILE_REGISTRY[name] = func
        return func
    return decorator


def available_delay_profiles() -> list[str]:
    """Names accepted by :func:`get_delay_profile`.

    Returns
    -------
    list of str
        Registered names, sorted. Includes any model the user added
        through :func:`register_delay_profile`.

    Examples
    --------
    >>> [name for name in available_delay_profiles() if name.startswith("E")]
    ['EPA', 'ETU', 'EVA']
    """
    return sorted(_PROFILE_REGISTRY)


def get_delay_profile(standard: str, **kwargs: Any) -> PowerDelayProfile:
    """Return a catalog delay profile by name.

    Parameters
    ----------
    standard : str
        Entry name, e.g. ``"EVA"``; see :func:`available_delay_profiles`.
    **kwargs
        Forwarded to the entry factory (e.g. ``doppler``).

    Raises
    ------
    KeyError
        If the name is not in the catalog.

    Examples
    --------
    >>> profile = get_delay_profile("ETU")
    >>> profile.n_taps, round(profile.rms_delay_spread_ns)
    (9, 991)
    """
    if standard not in _PROFILE_REGISTRY:
        raise KeyError(
            f"unknown delay profile {standard!r}; available: "
            f"{available_delay_profiles()} -- register your own with "
            f"@register_delay_profile")
    return _PROFILE_REGISTRY[standard](**kwargs)


def _check_expect(profile: PowerDelayProfile,
                  expect: Optional[dict[str, float]]) -> PowerDelayProfile:
    """Verify a catalog entry against figures published with its table (D20)."""
    if not expect:
        return profile
    checks = {
        "n_taps": float(profile.n_taps),
        "rms_delay_spread_ns": profile.rms_delay_spread_ns,
        "mean_delay_ns": profile.mean_delay_ns,
        "max_excess_delay_ns": float(profile.delays_ns[-1]),
    }
    for key, wanted in expect.items():
        if key not in checks:
            raise KeyError(f"unknown self-check {key!r}; known: {sorted(checks)}")
        got = checks[key]
        if abs(got - wanted) > max(0.5, 1e-3 * abs(wanted)):
            raise ValueError(
                f"{profile.standard}: expected {key} = {wanted} from "
                f"{profile.reference or 'the standard table'}, the table "
                f"above gives {got:.3f} -- one of the two was mistyped.")
    return profile


# 3GPP TS 36.101 Annex B.2 -- the LTE reference profiles. The summary
# table (B.2-1) publishes three figures per model: tap count, RMS delay
# spread, and maximum excess delay. EVA and ETU match all three, so both
# are pinned on all three.
#
# EPA matches two of three. Its tap count (7) and maximum excess delay
# (410 ns) come out exactly, but the RMS spread of this table is 43.13 ns
# against a published 45 ns. That gap was investigated rather than
# tolerated:
#
#   * the definition is not in question -- power-weighted and central,
#     the same one that reproduces EVA to 0.35 ns and ETU to 0.06 ns.
#     Amplitude weighting gives 69.8 ns, the second moment about zero
#     61.8 ns, the mean delay 44.2 ns: none of them lands on 45;
#   * no plausible transcription error bridges it either. Reaching 45 ns
#     would take +1.67 dB on the last tap, +3.83 dB on the 190 ns tap, or
#     +76 ns on the 410 ns delay -- none of which is a typo shape in a
#     table of round values.
#
# The tap count and the excess delay confirm the *delays*; the *powers*
# are not independently confirmed by the summary table, so the two least
# significant ones (-17.2 and -20.8 dB) are where a discrepancy would
# hide. Until someone reads Table B.2.1-1 itself, the entry pins the two
# figures it reproduces and leaves the third unasserted: pinning a number
# we cannot source would be worse than pinning none.

@register_delay_profile("EPA")
def _epa(**kwargs: Any) -> PowerDelayProfile:
    """Extended Pedestrian A (3GPP TS 36.101 Table B.2.1-1)."""
    return _check_expect(PowerDelayProfile(
        np.array([0, 30, 70, 90, 110, 190, 410], dtype=float),
        np.array([0.0, -1.0, -2.0, -3.0, -8.0, -17.2, -20.8], dtype=float),
        standard="EPA", reference="3GPP TS 36.101 Table B.2.1-1",
        **kwargs), {"n_taps": 7, "max_excess_delay_ns": 410})


@register_delay_profile("EVA")
def _eva(**kwargs: Any) -> PowerDelayProfile:
    """Extended Vehicular A (3GPP TS 36.101 Table B.2.1-2)."""
    return _check_expect(PowerDelayProfile(
        np.array([0, 30, 150, 310, 370, 710, 1090, 1730, 2510], dtype=float),
        np.array([0.0, -1.5, -1.4, -3.6, -0.6, -9.1, -7.0, -12.0, -16.9], dtype=float),
        standard="EVA", reference="3GPP TS 36.101 Table B.2.1-2",
        **kwargs), {"n_taps": 9, "rms_delay_spread_ns": 357,
                    "max_excess_delay_ns": 2510})


@register_delay_profile("ETU")
def _etu(**kwargs: Any) -> PowerDelayProfile:
    """Extended Typical Urban (3GPP TS 36.101 Table B.2.1-3)."""
    return _check_expect(PowerDelayProfile(
        np.array([0, 50, 120, 200, 230, 500, 1600, 2300, 5000], dtype=float),
        np.array([-1.0, -1.0, -1.0, 0.0, 0.0, 0.0, -3.0, -5.0, -7.0], dtype=float),
        standard="ETU", reference="3GPP TS 36.101 Table B.2.1-3",
        **kwargs), {"n_taps": 9, "rms_delay_spread_ns": 991,
                    "max_excess_delay_ns": 5000})


def validate_taps_fit(profile: PowerDelayProfile, fs: float,
                      n_samples: int) -> None:
    """Raise if the signal is too short to carry the profile's delays.

    Parameters
    ----------
    profile : PowerDelayProfile
        Model whose longest path must land inside the signal.
    fs : float
        Sampling rate in Hz, which fixes where the delays land.
    n_samples : int
        Length of the signal along the time axis.

    Raises
    ------
    ShapeError
        If the longest path lands at or beyond the last sample.

    Examples
    --------
    >>> profile = get_delay_profile("ETU")   # longest path at 5000 ns
    >>> validate_taps_fit(profile, fs=15.36e6, n_samples=1024)
    >>> validate_taps_fit(profile, fs=15.36e6, n_samples=32)
    Traceback (most recent call last):
        ...
    comnumpy.exceptions.ShapeError: expected at least 78 samples ...
    """
    max_delay = int(np.rint(profile.delays_ns[-1] * 1e-9 * fs))
    if n_samples <= max_delay:
        raise ShapeError(
            f"expected at least {max_delay + 1} samples to carry the "
            f"{profile.standard} profile at fs={fs:.3g} Hz (its longest "
            f"path lands on sample {max_delay}), got {n_samples} -- "
            f"lengthen the signal or raise the sampling rate.")
